# See https://www.chirpstack.io/docs/chirpstack-gateway-bridge/configuration.html for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]
username=""
password=""

[integration.mqtt]
event_topic_template="+/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template="+/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template="+/gateway/{{ .GatewayID }}/command/#"
