version: '3'

services:
  nginx:
    environment:
      CERTBOT_DOMAINS: "${CERTBOT_FQDN:-.}"
      CERTBOT_EMAIL: "${CERTBOT_EMAIL:-.}"
      NGINX_FQDN: "${NGINX_FQDN:-.}"
    build: .
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks:
  default: 
    name: chirpstack
    external: true