x-logging:
  &default-logging
  driver: 'json-file'
  options:
    max-size: "100m"
    max-file: "1"

services:

  chirpstack:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./docker-data/chirpstack:/etc/chirpstack
      - ./docker-data/certs/ca.pem:/etc/chirpstack/certs/ca.pem:ro
      - ./docker-data/certs/ca-key.pem:/etc/chirpstack/certs/ca-key.pem:ro
      # - ./lorawan-devices:/opt/lorawan-devices
    depends_on:
      - postgresql
      - mosquitto
      - redis
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgresql
    ports:
      - 8080:8080
    logging: *default-logging

  # chirpstack-gateway-bridge:
  #   image: chirpstack/chirpstack-gateway-bridge:4
  #   restart: unless-stopped
  #   ports:
  #     - 3001:3001
  #   volumes:
  #     - ./docker-data/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
  #     - ./docker-data/certs/ca.pem:/etc/chirpstack-gateway-bridge/certs/ca.pem:ro
  #     - ./docker-data/certs/basicstation.pem:/etc/chirpstack-gateway-bridge/certs/basicstation.pem:ro
  #     - ./docker-data/certs/basicstation-key.pem:/etc/chirpstack-gateway-bridge/certs/basicstation-key.pem:ro
  #   depends_on:
  #     - mosquitto
  #   logging: *default-logging

  chirpstack-gateway-bridge-basicstation:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-us915_0.toml
    ports:
      - 3001:3001
    volumes:
      - ./docker-data/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge:ro
      - ./docker-data/certs/ca.pem:/etc/chirpstack-gateway-bridge/certs/ca.pem:ro
      - ./docker-data/certs/basicstation.pem:/etc/chirpstack-gateway-bridge/certs/basicstation.pem:ro
      - ./docker-data/certs/basicstation-key.pem:/etc/chirpstack-gateway-bridge/certs/basicstation-key.pem:ro
    depends_on:
      - mosquitto

  postgresql:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./docker-data/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    logging: *default-logging

  redis:
    image: redis:7-alpine
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    restart: unless-stopped
    volumes:
      - redisdata:/data
    logging: *default-logging

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./docker-data/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./docker-data/eclipse-mosquitto/certs:/etc/mosquitto/certs
      - ./docker-data/eclipse-mosquitto/acl:/etc/mosquitto/acl
    logging: *default-logging

volumes:
  postgresqldata:
  redisdata:

networks:
  default:
    name: chirpstack
